### ISSUE TITLE
Potential error in country funding calculation

### ISSUE THREAD

**Issue by Player701** [OpenXcom/OpenXcom#1244]
I first mentioned this [on the forum](https://openxcom.org/forum/index.php?topic=6511.0) a few years ago as issue no. 2, but no developer has responded since. Guess I should have reported this as a bug right away.

**Synopsis:** There is the following comment in MonthlyReportState.cpp:

https://github.com/OpenXcom/OpenXcom/blob/a8080d499c811d56b44c8eb5cc1dced871e27d03/src/Geoscape/MonthlyReportState.cpp#L348-L349

As far as I understand it, this means that the score earned for completing research projects should not play a part in determining funding changes of countries. However, this comment and the actual code seem to disagree with each other. This is the part where funding amounts are updated:

https://github.com/OpenXcom/OpenXcom/blob/a8080d499c811d56b44c8eb5cc1dced871e27d03/src/Geoscape/MonthlyReportState.cpp#L368-L395

To be precise, this is the exact line where it happens:

https://github.com/OpenXcom/OpenXcom/blob/a8080d499c811d56b44c8eb5cc1dced871e27d03/src/Geoscape/MonthlyReportState.cpp#L380

And now look at how `xcomTotal` is calculated:

https://github.com/OpenXcom/OpenXcom/blob/a8080d499c811d56b44c8eb5cc1dced871e27d03/src/Geoscape/MonthlyReportState.cpp#L355

As we can see, it includes the research score. This value is passed to each country to influence its funding change, which contradicts the aforementioned comment (lines 348-349). Depending on whether or not this code is correct, one of the following should be done:

- If it's correct, the comment should be removed, because it is misleading.
- If it's wrong, then it should be fixed: my proposal is to change line 380 by replacing `xcomTotal` with `xcomSubTotal` (which is a sum of XCOM activity scores across all regions).

IMO, it doesn't really make sense to have research influence country funding, but I haven't done any reverse engineering on vanilla XCOM for that matter - maybe it really does work that way?

**Comment by Warboy1982** [comment]
the comment is misleading, but a code dive on the decompiled sources indicates that we're in-line with vanilla behaviour

**Comment by Warboy1982** [comment]
for reference:
```
  do
  {
    v0 += *(int *)((char *)&a_GS_xcom_DAT[16] + v14);
    v14 += 4;
    v291 += *(int *)((char *)&a_GS_alien_DAT[15] + v14);
    --v17;
  }
  while ( v17 );
```
reads as: tally xcom scores and alien scores, stored in v0 and v291 respectively
```
  v299 = (unsigned __int16)a_Graph_Monthly_Research_score[month_m1_1] + v0;
```
v0 is analogous to xcomSubtotal, v299 is analogous to xcomTotal
it then iterates through each country, using v299 exclusively to do their decision making, v0 is not referenced again after this point.

**Comment by Player701** [comment]
Thank you for clarifying this. If possible, please remove the comment then, so that other people working with the code don't get confused, like I was.
