### ISSUE TITLE
'installation instuctions' misses the openxom installation step

### ISSUE THREAD

**Issue by andreykurilin** [OpenXcom/OpenXcom#1246]
hi!

[Downloads](https://openxcom.org/downloads-milestones/) page doesn't include any link for downloading the actual OpenXcom project. Instead, it includes a link to *instruction* at [ufopaedia](https://www.ufopaedia.org/index.php?title=Installing_(OpenXcom) that includes only information about integration of OpenXcom with original x-com resources.

My question is where I should get OpenXcom? I can find links for nightly builds , but nothing for stable. Should I build openxcom from source code? Any instructions?

**Comment by Warboy1982** [comment]
get the nightly ;)
