### ISSUE TITLE
Most of SWS's in TFTD may have incorrect damage values

### ISSUE THREAD

**Issue by Player701** [OpenXcom/OpenXcom#1251]
**Synopsis:** There is a possibility that the damage values for most of TFTD's HWPs (or SWS's, as they are called there) may not match those found in the original game. 

I've noticed that for all SWS's except Displacer/PWT, the damage values listed in the corresponding articles at UFOpaedia.org do not match the values found in OpenXcom. Furthermore, almost every one of these articles features a small notice at the bottom saying that the value listed in the in-game UFOpaedia is incorrect, and the provided actual value has allegedly been taken directly from the game files.

While I have no means to confirm or deny whether these discrepancies actually exist, it would perhaps be worth verifying this information and potentially fixing the values in OpenXcom, for the sake of staying true to vanilla experience.

The affected SWS's are:

1. [Coelacanth/Aqua Jet](https://www.ufopaedia.org/index.php/Coelacanth/Aqua_Jet): 90 (incorrect value) vs 85 (purported actual value)
2. [Coelacanth/Gas Cannon](https://www.ufopaedia.org/index.php/Coelacanth/G._Cannon): 50 (incorrect value) vs 60 (purported actual value)
3. [Coelacanth/Gauss](https://www.ufopaedia.org/index.php/Coelacanth/Gauss): 120 (potentially incorrect value) vs 110 (potentially correct value) \*
4. [Displacer/Sonic](https://www.ufopaedia.org/index.php/Displacer_/Sonic): 130 (incorrect value) vs 110 (purported actual value) \*\*

\* This particular page does not mention any discrepancy between UFOpaedia and the actual value, but the listed value of 110 still does not match OpenXcom's provided value of 120.
\*\* UFOpaedia.org additionally states in the articles for [Bio-Drone](https://www.ufopaedia.org/index.php/Bio-Drone) and [Triscene](https://www.ufopaedia.org/index.php/Triscene) that the sonic weapon used by these aliens is exactly the same as the turret mounted on the sonic Displacer. Again, I cannot verify this on my end, but if it's true, then OpenXcom indeed provides the correct damage value of 110 for this weapon; however, the snapshot accuracy is off by 1 point (86 vs 85).

Quite surprisingly, I've found a commit from 3.5 years ago which contains changes to damage values for all of the HWPs from the list above: https://github.com/OpenXcom/OpenXcom/commit/07933b4e9c6979e6737c16cfd2b2a8b5e22f9d7a. Looking at the UFOpaedia.org edit history, the damage values for Coelacanth/Aqua Jet and Coelacanth/Gas Cannon were edited several months after the commit date. I can only assume that the correct values had initially been discovered by the OpenXcom team independently but were later changed to wrong ones for reasons unknown. Though perhaps it would be best to re-check everything to make sure?

**Comment by Player701** [comment]
**Update:** The data table found within [TACTICAL.EXE](https://www.ufopaedia.org/index.php?title=TACTICAL.EXE) from the Steam version of TFTD confirms that the values used in OpenXcom are not correct. The exact same table is also featured in [this UFOpaedia.org article](https://www.ufopaedia.org/index.php/Innate_Weapons_(TFTD)). It also lists the snapshot accuracy of Displacer/Sonic as 86 and not 85 (though the difference is probably negligible). The same applies to EU Hovertank/Plasma (OpenXcom's snap accuracy for it is 85 but the value in TACTICAL.EXE is 86).

**Comment by Player701** [comment]
Hey, thanks for looking into this! It seems that everything is now the same as in vanilla again. Balance has been restored to the universe! =)

**Comment by Warboy1982** [comment]
yeah, "balance"...
