### ISSUE TITLE
X-Com UFO Defense sound option not changing

### ISSUE THREAD

**Issue by JohnKloke** [OpenXcom/OpenXcom#1254]
Attempting to switch to version 1.4 sound effects. From Main Menu go into Options -> Audio. Choose 1.4 from drop down. Game reboots and shows 1.4 on the drop down box but next to current it says 1.0. In Game sounds effects are still version 1.0

**Comment by Player701** [comment]
I cannot reproduce this with the Steam version of UFO Defense on my Windows 10 machine. It looks like you need the following files in your OpenXcom\UFO\SOUND folder for version 1.0 SFX to work:

- SOUND1.CAT
- SOUND2.CAT

If you don't have these files, then you probably have the CE version, and you can only use version 1.4 SFX. So I don't think this is a bug.

**Comment by JohnKloke** [comment]
Greetings

I have loaded the Steam version to my PC (Windows 10) and can confirm that the issue I described does not exist. I am using the DOS version of the game, perhaps it wasn’t patched to version 1.4 like I believed it had been. I will investigate that side of it when I get a chance.

Thank you for investigating my ticket, my apologies if this turns out I just had the wrong version going.

John

**Comment by Player701** [comment]
Sorry, I misread your original post, I thought you couldn't get version 1.0 SFX to work. But I guess you understood me anyway. For 1.4/CE you need SAMPLE.CAT and SAMPLE2.CAT in your SOUND folder. In the unpatched DOS version these files probably don't exist, according to [this UFOpaedia.org article](https://www.ufopaedia.org/index.php/SOUND).

**Comment by JohnKloke** [comment]
Good evening,

I have managed to find the X-Con 1.4 patch and applied it to my base DOS install, and have re-run the latest nightly installer. It now shows 1.4 as current and plays the SFX for v1.4

My apologies for the wild goose chase.

John
