### ISSUE TITLE
Wrong HWP count in craft info

### ISSUE THREAD

**Issue by qx87** [OpenXcom/OpenXcom#1255]
1. Send X-COM craft to a battle mission with 4 HWPs.
2. Let aliens destroy one HWP or do it yourself.
3. When craft is returning to the base its info shows it still has 4 HWPs.

**Comment by SupSuper** [comment]
Did the HWP have a replacement in the base?

**Comment by qx87** [comment]
Yes

**Comment by qx87** [comment]
Why is it invalid?

**Comment by Warboy1982** [comment]
it was automatically replaced by the one in storage at the base, like any other piece of equipment would be.

**Comment by SupSuper** [comment]
Crafts are restocked instantly, not at base arrival. This is vanilla behavior.

**Comment by qx87** [comment]
Hmm... And what about https://openxcom.org/about/ ?
`Fixability: Play the game natively without any need for emulators or fancy hacks, with none of the limitations and **bugs that plagued the original**.`

**Comment by Warboy1982** [comment]
... it's not a bug though
