### ISSUE TITLE
I can drop a grenade through Triton wall

### ISSUE THREAD

**Issue by qx87** [OpenXcom/OpenXcom#1256]
In the beginning of a mission my aquanaut named Булкинс dropped a grenade through sub wall (just by mistake) and the drop was successful.
![DropThroughTritonWall](https://user-images.githubusercontent.com/16620214/82487608-084c3380-9af8-11ea-94b7-18297e6f70a4.png)

**Comment by Player701** [comment]
This is probably a map error. Are you using the [data patch](https://openxcom.org/download/extras/universal-patch-tftd.zip)? If not, please install the data patch and check if this still happens. I'm not sure, but you may need to start a new mission for that. If nothing changes, I suspect this will likely have to be fixed in the data patch itself, not the game code...

**Comment by qx87** [comment]
No, but after installing the bug still persists: both aquanauts near the arrow can drop their grenades out of the Triton.

**Comment by Player701** [comment]
Are you using the same save file? I think it's necessary to start a new mission after installing the patch, since the tile data gets saved too.

**Comment by SupSuper** [comment]
This is a bug in the original game logic, not the data. A fix will be coming shortly.

**Comment by SupSuper** [comment]
323659cf28c3e651a9e15542c02d87b62947cd92

**Comment by Player701** [comment]
OK, thanks. I didn't recall this happening neither in XCOM 1 nor in XCOM 2 in my own games, so I thought it was probably a map bug. Sorry then.

**Comment by qx87** [comment]
Now there is another situation.

When an aquanaut tries to drop grenade onto the second (third, etc) cell after the Triton wall, game shows a message that he cannot drop there.

But when he an aquanaut tries to drop grenade onto the cell just near the wall (neighbour cell) he DOES drop it underfoot. I believe the game should also show such a message.

**Comment by MeridianOXC** [comment]
When you shoot one tile behind a wall, the game also allows you to shoot, even though there is clearly no line of fire. Only if you go one tile further, the game doesn't let you.
Anyway, I'm not saying it's ideal, but you just can't fix everything. We will only make it worse if we continue poking into this issue. This bug went unnoticed for 25 years, let's call it good enough.
