### ISSUE TITLE
Compilation error for 8ae998af39abf6ea3f0619dacb79eb342ab83e8c

### ISSUE THREAD

**Issue by armijnhemel** [OpenXcom/OpenXcom#1260]
On Fedora 30, commit 8ae998af39abf6ea3f0619dacb79eb342ab83e8c

make[1]: Entering directory '/home/armijn/git/OpenXcom'
  CXX      src/Engine/openxcom-Screen.o
src/Engine/Screen.cpp: In member function ‘void OpenXcom::Screen::makeVideoFlags()’:
src/Engine/Screen.cpp:76:14: error: ISO C++ forbids converting a string constant to ‘char*’ [-Werror=write-strings]
   76 |   SDL_putenv("SDL_VIDEO_CENTERED=");
      |              ^~~~~~~~~~~~~~~~~~~~~
src/Engine/Screen.cpp:80:14: error: ISO C++ forbids converting a string constant to ‘char*’ [-Werror=write-strings]
   80 |   SDL_putenv("SDL_VIDEO_WINDOW_POS=");
      |              ^~~~~~~~~~~~~~~~~~~~~~~
src/Engine/Screen.cpp:81:14: error: ISO C++ forbids converting a string constant to ‘char*’ [-Werror=write-strings]
   81 |   SDL_putenv("SDL_VIDEO_CENTERED=center");
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/Engine/Screen.cpp:85:14: error: ISO C++ forbids converting a string constant to ‘char*’ [-Werror=write-strings]
   85 |   SDL_putenv("SDL_VIDEO_WINDOW_POS=");
      |              ^~~~~~~~~~~~~~~~~~~~~~~
src/Engine/Screen.cpp:86:14: error: ISO C++ forbids converting a string constant to ‘char*’ [-Werror=write-strings]
   86 |   SDL_putenv("SDL_VIDEO_CENTERED=");
      |              ^~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:4747: src/Engine/openxcom-Screen.o] Error 1
make[1]: Leaving directory '/home/armijn/git/OpenXcom'
make: *** [Makefile:7589: all-recursive] Error 1

**Comment by SupSuper** [comment]
But the signature of `SDL_putenv(const char *variable)` is a `const char`. Am I missing something?
http://sdl.beuc.net/sdl.wiki/SDL_putenv

**Comment by armijnhemel** [comment]
I have no idea, otherwise I would have provided a fix as well, sorry. I bumped into this, it seems to have been introduced in the latest commit.
