### ISSUE TITLE
disable firing choices depending on available TUs

### ISSUE THREAD

**Issue by nsklaus** [OpenXcom/OpenXcom#1261]
this is a feature suggestion:
what would think of disabling the firing choices that are not possible because there isn't enough time units left ?

for example, let's say i have 16 TUs left, i click on my weapon and i see the firing choices:
```
aimed shot :  TUs > 30
snap shot :   TUs > 15
auto shot :   TUs > 20
throw :       TUs > 15
```

there is only two possibilities: snap or throw.
why not graying out the two unavailable choice: aimed and auto ?
either gray out or completely remove from list. 
this could be optional tweak. i'll let you judge.

additionaly i'd like to take opportunity to say:  xcom is getting better than ever to play.
and this is no small thing. you're making it better without distorting it. you're keeping it true to its roots. 
among the many things you did, i like the option you folks made to have a tile, blocking line of fire, to blink for a few secs.
you're offering this old gem, a second youth. you're an example to follow. 
i just wish someone made the same treatment to fallout 1 and 2.
ok i go back cleaning alien terror site now..

**Comment by 0xebjc** [comment]
I'd recommend grey out vs hide, that way you can see... like "oh no!" I only have 16 TUs left and need 20 TUs for an auto shot... "I'd better remember to leave at least 20 TUs next turn if I want to auto shot"

**Comment by MeridianOXC** [comment]
This feature is not in scope of OpenXcom, nor OpenXcom Extended.

Closing as not planned.
