### ISSUE TITLE
Bug: wasted snapshot TUs after enemy melee reactions

### ISSUE THREAD

**Issue by MeridianOXC** [OpenXcom/OpenXcom#1263]
Meridian 06/19/2020
@OpenXcom Developer here is a save with the reproduced issue from #bugs-troubleshooting
Attachment file type: unknown
in_place.sav
321.66 KB

select the displacer, use snap shot and shoot the soldier on [34,14,0]
technician on [34,15,0] will react
then keep shooting... and observe the bug

Video: https://cdn.discordapp.com/attachments/330657487583838208/723448291878109244/lost_shots.mp4
Save: https://cdn.discordapp.com/attachments/330657487583838208/723447183709569064/in_place.sav

Picture showing which commit caused it: https://cdn.discordapp.com/attachments/330657487583838208/723817803047632906/unknown.png

**Comment by Warboy1982** [comment]
https://github.com/OpenXcom/OpenXcom/commit/09082d635cf937e795ee1b9d630ebcad05ff5843
