### ISSUE TITLE
Major slowdown if enemy becomes unconscious after secondary explosions

### ISSUE THREAD

**Issue by Caleb13-2** [OpenXcom/OpenXcom#1264]
Ever since I've started playing TFTD with OpenXCOM about 5 year ago, I occassionaly encountered a strange slowdown after some big explosions, mostly ones triggered by disruptor pulse launcher. I found that odd, since I generally play on pretty fast PCs (Threadripper 1950X now). I think I managed to narrow down the cause yesterday and I'm attaching a save file which can replicate it. This bug happens regardless of explosion height settings, though the save file was made with setting 3 (spherical explosions). I'm also attaching my config file, it makes replication on another PC much easier.  You need to do the following, it works with latest 2020-08-02 nightly and I had only built-in mods active:

1. Copy my config file, run the game and load the save file.
2. There is a MC'ed tasoth soldier which should be selected.
3. Use his DPL to fire a rocket. Now two scenarios can happen depending on where the rocket explodes.

4A. Scenario without slowdown. This is easiest to replicate if you fire the rocket at tentaculat at coordinates (30,35,1). This should happen:
-Main explosion.
-About 20 secondary explosions from railings.
-The MC'd tasoth and target tentaculat will die, their death sounds play immediately after the explosions stop.

4B. Scenario with slowdown. This is easiest to replicate if you fire the rocket into wall at coordinates (23,32,1). This should happen:
-Main explosion.
-About 20 secondary explosions from railings.
-Tasoth at coordinates (24,35,1) becomes unconscious.
-The game freezes for about 5 seconds, the player can't move the cursor, but music and smoke animations play as usual. On older PC with Intel i7-970 the game freezes for about 8 seconds.
-Tentaculat at coordinates (24,24,1) dies and its death sound is played.

Well, I'm not entirely sure if the secondary explosions are really a factor here, but AFAIR the slowdowns happened only with them. I always thought the exploding railings were odd, even back when I played vanilla TFTD.

[DPL slowdown.zip](https://github.com/OpenXcom/OpenXcom/files/5124072/DPL.slowdown.zip)

**Comment by MeridianOXC** [comment]
Debug info: the game generates 20+ UnitDieBStates for the same alien (Tasoth on [24,35,1]) and "animates" its death 20+ times, taking several seconds to do so.

**Comment by Caleb13-2** [comment]
> 
> 
> Debug info: the game generates 20+ UnitDieBStates for the same alien (Tasoth on [24,35,1]) and "animates" its death 20+ times, taking several seconds to do so.

BTW, aren't the exploding railings themselves a bug? It doesn't make much sense in the first place. It's no secret TFTD was made in great haste and in many instances, the creators just reused UFO asset definitions with new graphics. Lots of bugs were introduced into TFTD this way.

**Comment by Player701** [comment]
Exploding railings are definitely not an engine bug, though it could be a bug in the map data. If you don't have the [universal patch](https://openxcom.org/download/extras/universal-patch-tftd.zip) installed, you could download it and see if it provides a fix. If it doesn't, well... you'll have to live with this unless you can edit the maps yourself. Since we don't know what the map designer(s) had in mind, it's impossible to tell whether these explosions were added intentionally or by mistake. Personally, I don't consider this a bug, but I can see how others might think otherwise.

**Comment by Caleb13-2** [comment]
Yes, I have the universal patch installed and the railings still explode.

**Comment by Caleb13-2** [comment]
I encountered another such slowdown today, but the explosion was caused by my soldier, not MC'ed alien. So who causes the explosion is not a factor in the bug.

**Comment by Warboy1982** [comment]
fix't
