### ISSUE TITLE
Setting the settings back to default when playing a master mod reverts X-COM to xcom1 and relables the save file to xcom1

### ISSUE THREAD

**Issue by Tarkalak** [OpenXcom/OpenXcom#1265]
Reproduction:
1. Start a game with xcomfiles master mod (I assume it will be the same with any other)
2. Reset settings to default through the  button in the settings menu
3. Save the game and Exit X-Com completely and start it again
Failure 1: X-Com starts with xcom1 master mod instead of xcomfiles (not sure if bug)
Failure 2: The save is relabeled as
****
mods:
  - "xcom1 ver: 1.0"
****
instead of 
****
mods:
  - "x-com-files ver: 1.5"
  - "dark-geoscape ver: 1.0"
****

Also the save is in xcomfiles save folder and is not loadable until manually fixing it.

Tested with both Ironman and without.
![Screenshot from 2020-09-02 20-43-11](https://user-images.githubusercontent.com/1658731/92018743-37f91180-ed5e-11ea-8343-a997c87951dd.png)

**Comment by Tarkalak** [comment]
I am not sure if this is for here or for OXCE.

**Comment by MeridianOXC** [comment]
@SupSuper just remove the "Restore Defaults" button when in game (i.e. when SavedGame is not nullptr)?
