### ISSUE TITLE
Map generator encountered an error: no alien units could be placed on the map.

### ISSUE THREAD

**Issue by WierzbowskiH** [OpenXcom/OpenXcom#1269]
Steps to reproduce:
1. Load saved game. (attached)
2. Intercept crashed Marsian Battleship with Poseidon-1 from Main UK base.
3. Select "Yes" button to begin mission.
4. Error message pops up. (screenshot attached)

-->
![OpenXcomError](https://user-images.githubusercontent.com/71443034/93470489-487ac180-f8f2-11ea-841c-0830faa644a3.png)

[Martian Battleship BUGED.zip](https://github.com/OpenXcom/OpenXcom/files/5239046/Martian.Battleship.BUGED.zip)

**Comment by Warboy1982** [comment]
this is a problem with TWOTS, not openxcom, you'll need to post this on the mod page, not here.

**Comment by WierzbowskiH** [comment]
thanks. where do I find the mod page?

**Comment by Warboy1982** [comment]
https://openxcom.mod.io/the-world-of-terrifying-silence

same place you downloaded it ;)
