### ISSUE TITLE
Crash at end of final mission

### ISSUE THREAD

**Issue by dajt1725** [OpenXcom/OpenXcom#1275]
When I had one of my agents shoot the alien brain, the game promptly crashed with a segfault in OpenXcom::RuleItem::getPrisonType() const () (according to gdb)  I haven't had time to delve further, but I suspect having mind-controlled or stunned all the aliens might have something to do with it.

**Comment by dajt1725** [comment]
[c.zip](https://github.com/OpenXcom/OpenXcom/files/5311816/c.zip)
Here's the save file.

**Comment by MeridianOXC** [comment]
Can you link the mods too?
  - "selfheal ver: 1.0"
  - "Chryssalid tweaks ver: 1.0"
  - "ExtraBattleships ver: 1.1"
  - "First turn TU tweak ver: 0.8"
  - "GeoIconsUFO ver: 1.0"
  - "Lots more ufos ver: 0.1"
  - "Launcher Ammo ver: 0.1"
  - "Enhanced maps ver: 01"
  - "UFOpaedia-friendly Celatid ver: 0.9"
  - "vitals ver: 0.1" 

Especially the Chryssalid and Celatid mods.

**Comment by MeridianOXC** [comment]
There is a stunned celatid clone unit from the celatid mod, which cannot be recovered, because the corresponding geoscape item is missing. You can fix the mod by adding an item like this:

  - type: STR_CELATID_CLONE
    size: 0.0
    recover: true
    liveAlien: true
    costSell: 40000
