### ISSUE TITLE
Problem building against SDL2 on GNU/Linux

### ISSUE THREAD

**Issue by vanfanel** [OpenXcom/OpenXcom#1281]
Hi!

I am, for the first time, trying to build OpenXCom against SDL2, now that SDL2 has my new and shiny ATOMIC KMSDRM backend so DOS opensource games look like they did back in DOS, no X involved, etc :)

But I am seeing this while trying to configure the sources for building:

```
manuel@hp15db0:~/src/OpenXcom/b4$ cmake ..
CMake Error at cmake/modules/FindSDL2.cmake:187 (file):
  file failed to open for reading (No such file or directory):

    /home/manuel/src/OpenXcom/SDL_INCLUDE_DIR-NOTFOUND/SDL_version.h
Call Stack (most recent call first):
  cmake/modules/FindSDL2.cmake:278 (find_sdl_version)
  CMakeLists.txt:64 (find_package)


CMake Error at CMakeLists.txt:69 (message):
  Can't find SDL which is required


-- Configuring incomplete, errors occurred!
See also "/home/manuel/src/OpenXcom/b4/CMakeFiles/CMakeOutput.log".
See also "/home/manuel/src/OpenXcom/b4/CMakeFiles/CMakeError.log".

```

So, is OpenXCom even able to build against SDL2 at this point? Thanks!

**Comment by SupSuper** [comment]
Currently OpenXCom uses SDL1.2. There are forks using SDL2 you can try, but I don't know what their status is, eg.
https://github.com/sfalexrog/OpenXcom/tree/sdl2
https://github.com/MeridianOXC/OpenXcom/tree/android

**Comment by vanfanel** [comment]
@SupSuper Since SDL2 is virtually done on the Android port, are there no plans to merge SDL2 support? SDL1.x is legacy now...

**Comment by SupSuper** [comment]
It's a work in progress. The Android port modified a bunch of desktop features, so it's not as simple as just copying it over.
