### ISSUE TITLE
Incrementation bug in medikit related commendation.

### ISSUE THREAD

**Issue by Shoes01** [OpenXcom/OpenXcom#1287]
Currently the code reads:

https://github.com/OpenXcom/OpenXcom/blob/72af50720b3009351d6510bc1ef1066bbcab228a/src/Savegame/SoldierDiary.cpp#L218

but it should probably read `_woundsHealedTotal += unitStatistics->woundsHealed;`, as `unitStatistics->woundsHealed` is an `int`, not a `bool`.

**Comment by MeridianOXC** [comment]
Fixed in #1303
