### ISSUE TITLE
Replace Travis with Github Actions

### ISSUE THREAD

**Issue by SupSuper** [OpenXcom/OpenXcom#1293]
Travis charges money now, so it's useless to us:

![image](https://user-images.githubusercontent.com/603444/102034711-a23a3d00-3db6-11eb-94d0-06473c6817a1.png)

@uqs Can Travis be removed or is there still stuff to migrate to Github?

**Comment by uqs** [comment]
Right now, the only thing that Travis has over Github is the arm64 builds. It is missing some of the other bits, like testing `make install` as well as produces some downloadable artifacts.

So you could indeed stop using it. Beware the Github vendor lock-in though, they might also start charging at some point :)  Though I guess Microsoft's pockets are deeper than Travis' :)
