### ISSUE TITLE
[feature suggestion] In-game first-person view

### ISSUE THREAD

**Issue by brechtm** [OpenXcom/OpenXcom#1295]
I think it could be useful to be able to show the first-person view in-game, for quick line-of-sight checks. For example, as a new player of (Open)X-Com, I assumed a kneeling soldier could look over a seemingly low wall, but that turned out to be misleading after checking the FPS screenshot. Another situation where this would come in handy is when positioning a sniper at a window.

Is this something that could be considered for addition to OpenXCom, or does this stray too far from the original game? I understand the FPS screenshot feature is intended mostly for debugging purposes.

**Comment by MeridianOXC** [comment]
This is not in scope of OpenXcom.
(also not OpenXcom Extended)

maybe some other fork...

**Comment by MeridianOXC** [comment]
Closing as Won't Do.
