### ISSUE TITLE
game is not detected outside a predefined folder

### ISSUE THREAD

**Issue by ildar** [OpenXcom/OpenXcom#1299]
`openxcom -data /tmp/3/UFO` fails miserably

**Comment by R1dO** [comment]
Try with `openxcom -data /tmp/3/`.

The data flag specifies the parent folder containing (among others) UFO.
Also make sure `/tmp/3/` contains at least:
```
common
standard
TFTD  
UFO
```

Those are required for that flag to work properly (UFO **or** TFTD can be empty, depending which of those you are planning to run).

**Comment by MeridianOXC** [comment]
Closing as answered.
