### ISSUE TITLE
man6 wrong installation path on Linux

### ISSUE THREAD

**Issue by viy2** [OpenXcom/OpenXcom#1301]
man page should be installed to $PREFIX/share/man6, not to $PREFIX/man6
proposed patch:

--- a/docs/CMakeLists.txt
+++ b/docs/CMakeLists.txt
@@ -38,5 +38,5 @@ endif ()
 
 # Only useful for make install/package under *nix OSes, but not macOS.
 if ( UNIX AND NOT APPLE )
-    INSTALL(FILES ${CMAKE_CURRENT_SOURCE_DIR}/openxcom.6 DESTINATION ${CMAKE_INSTALL_PREFIX}/man/man6)
+    INSTALL(FILES ${CMAKE_CURRENT_SOURCE_DIR}/openxcom.6 DESTINATION ${CMAKE_INSTALL_PREFIX}/share/man/man6)
 endif ()

**Comment by uqs** [comment]
Oh god, looks like this is platform dependent. For FreeBSD the correct place indeed seems to be `/usr/local/man/`.

On my Debian, I have a symlink for `/usr/local/man` → `/usr/local/share/man`, so there, it doesn't matter. hier(7) on FreeBSD doesn't specifically talk about man-pages under /usr/local, but Debian's hier(7) has
```
 /usr/local/man
              Man pages associated with locally installed programs.
```

So this all seems correct for FreeBSD and Debian, what distribution are you running?

mandoc/mdocml which has been ported to many system defaults to this:
```
config.h
13:#define MANPATH_DEFAULT "/usr/share/man:/usr/local/man"
```

So I'm inclined to call this all working as intended?

**Comment by viy2** [comment]
I'm the official maintainer of openxcom in ALTLinux, see
http://ftp.altlinux.org/pub/distributions/ALTLinux/Sisyphus/files/SRPMS/openxcom-1.0_2020.10.10-alt1.src.rpm
openxcom is installed in /usr there. (/usr)/man is prohibited there. As of /usr/local, I think that you should use (/usr/local)/share/man instead of (/usr/local)/man too, because Filesystem Hierarchy Standard
( https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf , page 27, note 14) says: "/usr/local/man is deprecated and may be dropped in a future version of this specification"

**Comment by viy2** [comment]
I am not so sure for FreeBSD, but for flexibility, you can define and use CMAKE_INSTALL_MANDIR, for example. It is better for user to redefine a variable then to patch sources to fix installation.

**Comment by uqs** [comment]
To be honest, I think it's best to simply drop the installation of the man page and let per-distribution maintainers deal with it. I mean, it isn't even being compressed and cmake doesn't provide any helpers around that.

So far, it probably has caused more people to send in PRs than there are people that actually type out `man openxcom` and read even half of it :(

**Comment by viy2** [comment]
sorry for all the bother. 
> I think it's best to simply drop the installation
works for me.
