### ISSUE TITLE
Game crashing when entering a mission, using OpenXcom Extened 5.6.1 and X-Com Files v0.9.9e

### ISSUE THREAD

**Issue by Toad22484** [OpenXcom/OpenXcom#1305]
Hi everyone, I am uncertain if this has been fixed in the newer versions or not but as I was playing it last I got an error which I will post a screen shot of below.  It says "OpenXcom has crashed: Random item STR_MUTANT_BLOOD_PLASMA is outside of map block STORMMOUNTAIN04, position: [12,6,0], block size: [10,10,4]

![OpenXcom Error](https://user-images.githubusercontent.com/43642461/106084026-5b887400-60d2-11eb-98d5-849a9a916ab2.png)

I will also be attaching the log file and the save file below, the version of openxcom I am using is OpenXcom Extended 5.6.1.  I fear I may just be using older versions of these things but wanted to report just in case.  The error triggers when entering the "Cyberweb Heist" mission.

![openxcom cyberweb](https://user-images.githubusercontent.com/43642461/106084059-6ba05380-60d2-11eb-90e4-23ac53923fa4.png)

[Game Crash Save.zip](https://github.com/OpenXcom/OpenXcom/files/5884490/Game.Crash.Save.zip)

**Comment by MeridianOXC** [comment]
Yes, this has been fixed in a newer XcomFiles version.
