### ISSUE TITLE
Interceptor Stuck without fuel

### ISSUE THREAD

**Issue by jimhgit** [OpenXcom/OpenXcom#1309]
[2ND-GEOSCAPE.zip](https://github.com/OpenXcom/OpenXcom/files/6037029/2ND-GEOSCAPE.zip)
Interceptor got stuck near Australia after chasing a battleship out into the Pacific. I think having fast forward set to 1 day might have caused it.
Edit:
This is regular openXcom. No mods. Using nightly build 2020_11_25_1755

**Comment by MeridianOXC** [comment]
I can see the issue in the save file, but I cannot explain how it happened :(
Cannot reproduce locally.
Closing for now, can be reopened if we get any new reports.
