### ISSUE TITLE
At the end of "rearming", I lose Elerium even if fuel was 100% and all I did was switch a craft weapon.

### ISSUE THREAD

**Issue by MarkusRamikin** [OpenXcom/OpenXcom#1311]
Tested using both an Avenger or Firestorm, after resetting options and using no mods.

1. Craft sitting in base at 100% fuel and Ready status. Check Elerium stores.
2. Send the Craft into "Rearming" by removing a craft weapon and putting it back on, or just switching to a different weapon.
3. Once the craft is "Ready" again, check Elerium remaining. 1 unit will be missing.

**Comment by MeridianOXC** [comment]
PR #1317
