### ISSUE TITLE
CopyPaste error and out of bounds error

### ISSUE THREAD

**Issue by ZanyXDev** [OpenXcom/OpenXcom#1314]
To upper string **wa** , size check **wb**
Out of bounds access of wb, index 'wb.size()' is out of bounds.
https://github.com/OpenXcom/OpenXcom/blob/323659cf28c3e651a9e15542c02d87b62947cd92/src/Engine/Unicode.cpp#L307

**Comment by SupSuper** [comment]
Nice catch
