### ISSUE TITLE
Incorrect Intercept music behavior in TFTD

### ISSUE THREAD

**Issue by starslab** [OpenXcom/OpenXcom#1333]
I've confirmed with the Steam/DosBOX release of Terror From The Deep, that the game will alternate between and play 4 different intercept musics.

GMINTER1
GMINTER2
GMINTER3
And the mission brief music, GMISPOSH

The default xcom2 ruleset currently only plays GMINTER1, GMINTER2, and GMINTER3

**Comment by MeridianOXC** [comment]
I can confirm GMISPOSH being played also on the GOG.com/DosBox version.

But I don't think this is something that needs to be fixed on the engine level. A sound mod can easily be created with GMISPOSH copied and renamed to GMINTER4.

**Comment by starslab** [comment]
Can this be fixed at the default ruleset level? Fixing with a sound mod copy/paste will require every music pack for TFTD to issue an update.

**Comment by MeridianOXC** [comment]
I can't think of a way how to fix it just by ruleset.
Support for such new ruleset would need to be added to the engine.

**Comment by SupSuper** [comment]
Fixed in 8e5869d2b7695182208d8fa7ae879ae099e5a685
