### ISSUE TITLE
[PC only, Ironman cheating]Pressing Alt+F4 during Alien Turn or right before getting killed resets to player control without reverting progress.

### ISSUE THREAD

**Issue by panzernoob** [OpenXcom/OpenXcom#1335]
I've been playing on Superhuman Ironman and I've discovered that closing the game using Alt+F4 right before a soldier begins a death animation or during the alien's turn returns control to the player without undoing any actions taken during the turn. Aliens who are mind controlled can see other aliens movement and closing the game allows the player to mind control aliens who moved during the Alien's turn. Pressing Alt+F4 right before taking damage or going into a death animation can be abused to ignore damage. This glitch can also crash the game in various ways such as controlling a soldier who was stuck in a firing animation, not aliens though. On three occasions ending a glitched turn caused some error that I forgot to note and on one occasion caused a Segmentation Fault. 
-->

**Comment by panzernoob** [comment]
I streamed the game for a bit, I used this glitch over and over, eventually the game softlocked.
https://www.twitch.tv/videos/1218183906

**Comment by Warboy1982** [comment]
solution: disable ironman mode.

**Comment by panzernoob** [comment]
Why would I ever do that lel

**Comment by MeridianOXC** [comment]
When pressing Alt+F4 in such situation (and in many many other situations), you are forcing the game to save an invalid state. A state, which is not supported and cannot be anticipated by developers. The game tries to recover as good as it can, but it will inevitably fail in certain cases. In many other cases, it won't even recover and will start crashing.

If you want to keep Alt+F4-ing randomly, we suggest you turn Ironman off.
