### ISSUE TITLE
Mind controlled aliens who die in an explosion that destroys walls can see aliens on the other side before dying.

### ISSUE THREAD

**Issue by panzernoob** [OpenXcom/OpenXcom#1336]
Aliens who are mind controlled and facing a wall with characters on the other side will have a line of sight to characters on the other side **before** they die in an explosion.
-->

**Comment by MeridianOXC** [comment]
Same applies to units which are not mind controlled, and units from other factions, including xcom soldiers.
Same behavior tested in OG, OXC and OXCE.
It may be a bit weird, but it's true to XCOM.
Closing as not a bug.
