### ISSUE TITLE
TFTD Artefact Sites vs Ship Attacks

### ISSUE THREAD

**Issue by Player701** [OpenXcom/OpenXcom#1339]
Decided to play TFTD and was wondering why I wasn't getting any Artefact Site missions - those ones were among the most difficult because I distinctly remember them popping up quite early in the game, around March-April, and were quite easy to fuck up due to lack of better armor and MC resiliency at that time. I got a couple ship attacks in the meantime though, which I don't remember popping up until late-game.

So I tried to find out how the game determines when to generate such missions, and, apparently, according to the standard ruleset, these missions are not supposed to begin until June (or July, if months count from 0):

https://github.com/OpenXcom/OpenXcom/blob/4251ab7c88bc2cc7952c5cb6d559a97e588f6e0e/bin/standard/xcom2/missionScripts.rul#L58

And ship attacks start in March (or April if counting from 0), it seems:

https://github.com/OpenXcom/OpenXcom/blob/4251ab7c88bc2cc7952c5cb6d559a97e588f6e0e/bin/standard/xcom2/missionScripts.rul#L77

Perhaps these values have been swapped by accident? Of course I'm speaking only from my own experiences so I could be mistaken, but if possible, please re-check. Thank you very much!

**Comment by MeridianOXC** [comment]
a/ My last campaign Steam/DosBox:

April - nothing
May - shipping route
June - shipping route
July - artefact site
August - artefact site
September - nothing
October - artefact site
November - nothing
December - shipping route

b/ Testing GOG.com/DosBox:

1st June mission: (10 reloads end of May)
nothing 2x
shipping route 6x
nothing 1x
shipping route 1x

1st July mission: (10 reloads end of June)
shipping route 1x
artefact site 5x
shipping route 1x
nothing 1x
artefact site 2x

I think it's pretty safe to say the OpenXcom settings are correct.
