### ISSUE TITLE
Inclusion in F-Droid Android app repository

### ISSUE THREAD

**Issue by Hiradur** [OpenXcom/OpenXcom#1340]
[Since the Android repository of OXCE](https://github.com/MeridianOXC/openxcom-android) doesn't have issue tracking, I'm asking here, I hope that's ok.

[From the F-Droid webpage](https://f-droid.org/):
> F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device.

It would be great to have OXCE on F-Droid for simplified installation, maintenance (updates) and also to potentially increase its reach.
One of the [inclusion criteria](https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy) appears to be that the authors of the software know of the inclusion and support it. I hereby ask if you would support such an inclusion. I guess this question concerns all OpenXcom and OXCE developers and is specifically aimed at @sfalexrog and @MeridianOXC since they seem to be responsible for the Android port of OXCE.

Additionally, clarification on the license of the Android port of OXCE would be necessary. From what I understand, the [OpenXcom code is licensed under GPLv3](https://github.com/OpenXcom/OpenXcom/blob/master/LICENSE.txt). [The same applies to the PC version of OXCE](https://github.com/MeridianOXC/OpenXcom/blob/oxce-plus/LICENSE.txt). The README of [OpenXcom](https://github.com/OpenXcom/OpenXcom/blob/master/README.md) and [OXCE](https://github.com/MeridianOXC/OpenXcom/blob/oxce-plus/README.md) additionally states: "Uses modified code from SDL_gfx (LGPL) with permission from author.".
However, the [Android-specific repository of OXCE](https://github.com/MeridianOXC/openxcom-android) seems to lack licensing infomation.
The game assets are under a proprietary license and need to be obtained separately but that should not be an issue as long as they are not included with the application.

Should I receive a positive response from you, I would create a request for packaging at the [appropriate F-Droid issue tracker](https://gitlab.com/fdroid/rfp/-/issues). I already wrote a draft for this request, please check if the information is correct in case you are ok with inclusion.

```
### Link to the source code:
https://github.com/MeridianOXC/openxcom-android/tree/oxce-plus-proto

### Link to app in another app store:
N/A
APK Download: https://openxcom.org/forum/index.php/topic,5258.0.html

### License used:
Needs clarification.

### Category:
Games

### Summary:
Reimplementation of the UFO: Enemy Unknown (X-Com: UFO Defense in the USA) game engine

### Description:
OpenXcom Extended (OXCE) is an extended version of OpenXcom, which in turn is a reimplementation of the game engine used by UFO: Enemy Unknown (X-Com: UFO Defense in USA). OXCE changes some game mechanics compared to OpenXcom, more information can be found [here](https://openxcom.org/forum/index.php/topic,6459.0.html). OXCE supports mods.

Antifeatures: 
- Non-Free Assets: Game files from UFO: Enemy Unknown (X-COM: UFO Defense in the USA) and/or X-COM: Terror from the Deep are required in order to play. These are not included and have to be obtained elsewhere.

### Project website:
https://openxcom.org/forum/index.php/board,22.0.html
```

**Comment by SupSuper** [comment]
Seems fine by me. OXC and all derivatives should be under GPLv3, even if not explicitly stated.

**Comment by MeridianOXC** [comment]
ok from me too, feel free to do it
(license is GPLv3)

**Comment by sfalexrog** [comment]
I'm fine with this as well, though I haven't really touched anything for a while (and thus not sure whether I have a say in the matter).

**Comment by Hiradur** [comment]
I'm happy about the positive responses. I created a [request for packaging OXCE at their issue tracker](https://gitlab.com/fdroid/rfp/-/issues/1809).

**Comment by SupSuper** [comment]
@Hiradur These files don't really have a "license" AFAIK:
`app/src/main/assets/9_ufo-patch.zip` is a data patch for the original games, it's optional in case this is an issue.
`app/src/main/assets/z_nomedia.zip` seems to be empty? No idea what's it for.

**Comment by MeridianOXC** [comment]
Closing as answered.
