### ISSUE TITLE
Confused about SDL2 support

### ISSUE THREAD

**Issue by vanfanel** [OpenXcom/OpenXcom#1342]
HI there,

I was about to try and build OpenXCom on Debian 10 aarch64 (Pi4), where SDL2 works great without X11 (using the KMSDRM backend).

Now, I saw there's an SDL2 branch on this repo, but it seems to be outdated, and in the other hand, I can't see SDL2 support on the main branch.
So, what's the situation? Is the SDL2 branch the way to go? Or maybe it's just a matter of SDL2 branch to master merging not being done yet?

Thanks!

**Comment by MeridianOXC** [comment]
SDL2 branch is purely experimental atm. You can safely ignore it.

**Comment by vanfanel** [comment]
@MeridianOXC Ok, ok! I will wait then :)
Thanks for taking the time to answer!
