### ISSUE TITLE
[Suggestion] Show a of time or globe with light/dark on mini icon pre-mission equip screen

### ISSUE THREAD

**Issue by 0xebjc** [OpenXcom/OpenXcom#1343]
[Scenario]
When setting a craft with crew to intercept mission and not active watching the craft intercept the landing site often the pre-mission equip screen comes up and I have no idea if it's currently night or day at the landing site.  This usually happens when on geoscape the set time to 1 hour or 1 day and time passes too quickly.

[Issue]
Having no idea what time it is prevent making better informed decisions of what to equip the soldier with, like light emitting items, flares, flashlight, etc...

[Suggestion/Idea]
Would be nice to have a small icon on the pre-mission equip screen showing the glob at the current location with the right time of day, like is it dark/night or light/day, or even a clock showing the time of day at mission location and weather it's dark or light out.

**Comment by MeridianOXC** [comment]
This feature is already available in OpenXcom Extended (OXCE).
On the landing confirmation screen, we can display icons indicating:
1/ day
2/ dusk/dawn
3/ night
More info: https://openxcom.org/forum/index.php/topic,2408.msg61729.html#msg61729

**Comment by MeridianOXC** [comment]
Closing as done.
