### ISSUE TITLE
Debug explosions

### ISSUE THREAD

**Issue by TCH68k** [OpenXcom/OpenXcom#1345]
I've made a patch for OpenXcom which allows the player to create test explosions in debug mode:
http://oscomp.hu/depot/OpenXcom-DebugBlast.patch

It has two options, `debugBlast` which is the power of the explosion and `debugBlastStep` which is used, when the player changes the former option in the game by Ctrl + Plus and Ctrl + Minus. Trivially + increments `debugBlast` by `debugBlastStep` and - decrements it. It handles two modifiers, Shift and Caps Lock. When Shift is pressed, the change will be multiplied by 16. When Caps Lock is on the change will be multiplied by 256. At both, 4096.

The explosion can be made by Ctrl + B.

**Comment by MeridianOXC** [comment]
I am not interested in this feature, but I've at least shared it on the forum for other people who might want to include it in their forks: https://openxcom.org/forum/index.php/topic,10712.0.html
