### ISSUE TITLE
Cannot load savefile.

### ISSUE THREAD

**Issue by CharlzKlug** [OpenXcom/OpenXcom#1348]
I'm using Gentoo. I have installed OpenXCom from portage. OpenXCom version:

> charlzk@Scarlett ~ $ emerge --search openxcom
>   
> [ Results for search key : openxcom ]
> Searching...
> 
> *  games-engines/openxcom
>       Latest version available: 1.0.0_p20180317-r1
>       Latest version installed: 1.0.0_p20180317-r1
>       Size of files: 2 736 KiB
>       Homepage:      https://openxcom.org/
>       Description:   Open-source reimplementation of the popular UFO: Enemy Unknown
>       License:       GPL-3+ CC-BY-SA-4.0
> 

Unable to load savegame files.

How to reproduce: start new game, save game, try to load the savegame file. My save file: http://transfer.sh/lCCJ9H/t1.sav

**Comment by CharlzKlug** [comment]
charlzk@Scarlett ~ $ openxcom 
openxcom: /var/tmp/portage/games-engines/openxcom-1.0.0_p20180317-r1/work/OpenXcom-ea9ac466221f8b4f8974d2db1c42dc4ad6126564/src/Savegame/SerializationHelper.cpp:58: int OpenXcom::unserializeInt(Uint8**, Uint8): Assertion `false' failed.
Core dumped.

**Comment by MeridianOXC** [comment]
You probably need to downgrade your yaml-cpp to 0.6.x, since 0.7.x is currently broken.

**Comment by CharlzKlug** [comment]
Thank you! It works!

**Comment by DBLaci** [comment]
I filed an issue on Gentoo bugzilla as I couldn't found one: https://bugs.gentoo.org/827176

**Comment by CharlzKlug** [comment]
> I filed an issue on Gentoo bugzilla as I couldn't found one: https://bugs.gentoo.org/827176

Many thanks!

**Comment by DarthGandalf** [comment]
> You probably need to downgrade your yaml-cpp to 0.6.x, since 0.7.x is currently broken.

Any details? Is there an upstream bug?

**Comment by MeridianOXC** [comment]
> Any details? Is there an upstream bug?

Saving/loading of Uint8 is broken.
I don't know if there is any upstream bug.

**Comment by SupSuper** [comment]
There's an issue here: https://github.com/jbeder/yaml-cpp/issues/1027

Workarounds here:
https://github.com/OpenXcom/OpenXcom/commit/7fe2dd93bfe590250c563257cd078e8df519bfec
https://github.com/OpenXcom/OpenXcom/commit/09f8473bc8b91592db01e64fbc6cec7921a2b8ff
