### ISSUE TITLE
Impossible revert to 640x400 resolution

### ISSUE THREAD

**Issue by roman-kolo** [OpenXcom/OpenXcom#1351]
Impossible to set resolution to 640x400 if it was changed.

Reproduction:
1. Install game with default settings, altrernativaly delete settings file 'options.cfg'.
2. Start game, open settings.
3. Default resolution should be 640x400, change resolution to any other.
4. Try to set 640x400 -> its not in list.

To set back 640x400 one may change it directly in 'options.cfg'.

![qq](https://user-images.githubusercontent.com/32853157/148104774-dfe29eca-eca9-4afa-a11e-d586d487a75c.png)

**Comment by SupSuper** [comment]
You can click the numbers to set it back to 640x400 (or even 320x200). We can only list resolutions supported by your monitor, and no monitor indicates 640x400 anymore (a lot don't even show 640x480 anymore).

**Comment by roman-kolo** [comment]
But I play on 640x400 and it works perfectly. Any other resolution looks worse! My default monitor resolution is 1920x1080 and 640x400 perfectly streches onto my monitor (at least it looks so)

**Comment by roman-kolo** [comment]
Perhaps if game already starts with 640x400 it would be possible to add this resolution to list as always available?
