### ISSUE TITLE
HUGE amount of Items lost on two-part mission [TFTD]

### ISSUE THREAD

**Issue by katastic** [OpenXcom/OpenXcom#1354]
Everything that stored in my Triton, and perhaps more [the entire map?], was all lost.

I did a two-part Terror Cruise Ship and after 2-3 hours of onslaught, I survive, only to find out all my items were "lost" in the mission even though I successfully completed the first part. It remembered captured aliens.

![image](https://user-images.githubusercontent.com/11449593/153147746-778f5198-981e-4a01-977b-818d005b3d35.png)

![image](https://user-images.githubusercontent.com/11449593/153147688-4344af38-a216-40e7-8a73-a935d9fc9818.png)

All of my torpedo's (and other water only equipment) were left on the ship. And then "lost". I'm actually kind of screwed now in campaign because of the amount of losses I have to replace followed by immediate new ships.

It did appear to remember all captured aliens (though I haven't recounted, but it was certainly a high number and that's a high number):

![image](https://user-images.githubusercontent.com/11449593/153148645-c5246476-d23b-4dde-854e-b87e80016198.png)

I don't know if there's an easy way to tell from the stat screen whether it "lost" some of the alien dropped items as well.

**Comment by Warboy1982** [comment]
do you have a save file from during the mission?

**Comment by Warboy1982** [comment]
failing that, looks like you recorded it, any chance i can get a look at the footage?

**Comment by katastic** [comment]
Here should be two save files from the start of the boat, and the start of the next round.

[xcom2.zip](https://github.com/OpenXcom/OpenXcom/files/8038748/xcom2.zip)

**Comment by MeridianOXC** [comment]
From the second save I can see that the items didn't make it to stage 2, which means they were destroyed already in stage 1. Most likely by an explosion... a rogue rocket, forgotten grenade, or a dying biodrone. Could have exploded also outside the open craft doors, or through some holes in the triton.

Without a save just before end of stage 1, it is hard to be 100% sure though.

Closing as answered.
