### ISSUE TITLE
[Minor Feature] Keybindings for base systems

### ISSUE THREAD

**Issue by katastic** [OpenXcom/OpenXcom#1355]
Given this screen:

![image](https://user-images.githubusercontent.com/11449593/153883286-426cca38-a636-435b-ba50-53ee079787fd.png)

We could support:

 - "I" for Base (I)nformation
 - "A" for (A)quanauts
 - "E" for (E)quip Submarine
 - "B" for (B)uild Facility
 - "R" for (R)esearch. 
 - "M" for (M)anufacturing
 - "T" for (T)ransfer
 - "P" for (P)urchase/Recruit
 - "S" for (S)ell/Sack

Some of the most common ones at least are straight forward. This would go with the already 1, 2, 3, ..., 8  keys for selecting base number.

The only ones not listed bound are:

 - "Build a new base" that's a rare button to press, and 'N' could work. It's just not lined up with the first letter.
 - Geoscape (which is bound to ESCAPE

Other pages could also have key bindings such as R for research, then N for (n)ew project, and up/down arrows for selecting keys.

![image](https://user-images.githubusercontent.com/11449593/153884396-3a0889b3-8286-4f73-8e39-ede293ca59a9.png)

For some people, keyboard bindings are much more accessible and nature to use. 

I'm not familiar with your codebase, I could take a stab and making a pull request. If so, feel free to suggest where in the codebase to look for key binding, and menus.

Thanks, 
  --Chris

**Comment by MeridianOXC** [comment]
This feature is already available in OpenXcom Extended (OXCE): https://github.com/MeridianOXC/OpenXcom/commit/7eceeb46805a7e178323dbe4e950bc3a47cc334c

Download here: https://openxcom.org/forum/index.php/topic,5258.0.html

**Comment by MeridianOXC** [comment]
Closing as done.
