### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1356]
During intro if I click mouse button or press a key.
Also after intro is done:

Exception thrown at 0x7717C5AF in OpenXcom.exe: Microsoft C++ exception: OpenXcom::Exception at memory location 0x0945E7F4.

**Comment by SkybuckFlying** [comment]
This may be related to the sound issue...

**Comment by MeridianOXC** [comment]
Yes, this could be related to audio issues. #1357 was however closed as cannot reproduce, so closing this one too.
