### ISSUE TITLE
Floater arm has wrong position

### ISSUE THREAD

**Issue by bohemond-of-antioch** [OpenXcom/OpenXcom#1359]
A floater that holds an item has its arms 2px higher than they should be.
I can't confirm if this is also how it looks in pure original XCom.
I've found a screenshot from vanilla(allegedly) OpenXCom that confirms it:
![VanillaGameScreenshot](https://user-images.githubusercontent.com/79767825/157841643-47ccd2fd-1867-4254-880b-99c7c40616ba.png)

I've highlighted the issue in UnitSpriteStudio:
**Current graphics**
![Floater_3_ArmHigh](https://user-images.githubusercontent.com/79767825/157841773-a97cf504-018f-4687-a4eb-cdad76d626eb.png)
![Floater_5_ArmHigh](https://user-images.githubusercontent.com/79767825/157841787-6b9b55ab-cc06-437e-81b1-a09cbac62a23.png)

**How it should look(IMHO)**
![Floater_3_ArmNormal](https://user-images.githubusercontent.com/79767825/157841845-2751baf1-aadb-42c7-bbb6-2b3d9b8d975c.png)
![Floater_5_ArmNormal](https://user-images.githubusercontent.com/79767825/157841861-d45f7bb9-c768-4bda-9239-c12d06dba457.png)

The asset I'm using to demonstrate the issue in UnitSpriteStudio is not original graphics, but it's a recolor of the original sprite and is good enough to show the problem.

**Comment by MeridianOXC** [comment]
OpenXcom:
![image](https://user-images.githubusercontent.com/8505318/183884708-59372435-e8fd-4f7b-8611-359584b7ab5f.png)

DosBox:
![image](https://user-images.githubusercontent.com/8505318/183884785-b4f4b459-9261-4c18-a127-d394ea0e6b3b.png)

**Comment by MeridianOXC** [comment]
The same issue is observable in the original xcom.

Fixing the drawing routine will likely break all mods using that routine for floater derivatives and other units.

I suggest fixing this by mods only.
