### ISSUE TITLE
Cannot close door when inside building and door went outside.

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1361]
Not sure if original allowed to close door when inside a building and door went outside.

Would be cool if it were possible in OpenXCom !

This would be usefull to hide from ethereals or other spotter units to try and prevent mind control ! (I assume mind control can only work if units spotted/visible to aliens ?! ;) If not implement that too ! =D)

See attached picture for problem.
![CannotCloseDoorWhenInsideBuildingsAndDoorIsOutside](https://user-images.githubusercontent.com/34254801/158076681-44750bb1-3bb6-409d-b9bb-306e44141b37.png)

**Comment by Warboy1982** [comment]
original did not allow for this, beyond walking into the tile and right clicking on the door from there, which is how you must do it here too

**Comment by SkybuckFlying** [comment]
Reaching for the door may seem to make sense at first glance, but walking out does not make any sense. Cannot close the door while inside apperently. This should be a considered a short coming and bug of the original, and here is where OpenXCom can improve to offer a more interesting play experience, more scary and more deep... think of Aliens opening doors, very scary ;)
