### ISSUE TITLE
Would be cool if alien or human bullits could be scrolled.

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1362]
Currently the screen freezes if bullits are animating/firing.

Would be cool if the user can scroll the screen with the mouse during this action to see better what is going on around the bullit.

**Comment by Warboy1982** [comment]
there's an option called "Smooth Bullet Camera" that should cover this, manual scrolling while a projectile is in flight wouldn't work out too well

**Comment by SkybuckFlying** [comment]
Freezing or auto following bullits takes away control of the user, it's an inferior experience.

Especially when the bullits fly slower, because of settings.

Being able to scroll while bullits fly, will give the users more sense of freedom and truely being in control of the game, as a god.
