### ISSUE TITLE
Fast placement mode (double/extra click while unit already moving/walking)

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1363]
I think the original xcom or tftd had a special functionality where deploying units could be speed up as long as there were no aliens and maybe on second mouse click to.

I am not sure how it worked in original I think I double/extra click while the unit was already moving would speed it up and place it at the end position, basically the game would compute the game logic and only halt if alien spotted or alien reaction fire occured or something like that.

This would be incredibly usefull to have for fast deployment from sky ranger !

**Comment by Warboy1982** [comment]
i don't remember any such function in either of the originals, you could just max out the player movement speed though?
for what it's worth, hidden aliens move almost like this, skipping all animations and simply teleporting one tile at a time to carry out vision/reaction logic. this is the fastest units can move.

**Comment by SkybuckFlying** [comment]
Then you never played the original seriously, it's a very obvious feature of the game. Download the original play, with dos-box-x.

It's a very easy to see feature... the soldier skips the movement for the tiles which are not visible.

No double click is necessary just single click.
