### ISSUE TITLE
options.cfg and debug mode and first person view not working while in visual studio.

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1364]
For some reason setting options.cfg:
debug: true

and then in game 
control-d 
F10 

Produces black first person view PNGs... it does write the file, but everything is black ? What is causing this ?

The files which visual studio seem to be using are located in:
C:\Users\new\Documents\OpenXcom

While the source code is in:

E:\SourceCode\OpenXCom\OpenXcom

Binary would be in:
E:\SourceCode\OpenXCom\OpenXcom\bin\Win32\Debug

I suspect this has something to do with... 

Perhaps this feature loads some graphics and expects it to be in a certain folder ? Otherwise I am somewhat mystified.

**Comment by MeridianOXC** [comment]
Tested with Visual Studio Community Edition 2022 v17.2.5
Works fine.
Closing as cannot reproduce.
