### ISSUE TITLE
Humans/Civilians could scream when/while on fire.

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1365]
I just saw some aliens put some humans on fire/civilians. Could be cool if they started screaming from time to time... maybe especially when they are moving lol.

But even when player is idling it would be cool.

Perhaps different noises:

When idling it softly moans and screams...

When running/moving it's like eh eh ah ah ah ah it burns... aahhhh help me aahhhhh that be cool ! =D

Maybe the sound effect of the game/first person shooter blood could be used !

It has some nice vocals for that ! ;) =D

**Comment by Warboy1982** [comment]
not legally possible to package up sounds from another game, also this would get very annoying

**Comment by SkybuckFlying** [comment]
It could be done occasionally to prevent it from becoming annoying.
