### ISSUE TITLE
Shift should be used to queue blaster launcher bombs. Could also be used to go to previous unit. Add movements and even realtime gameplay !

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1366]
For windows users it will feel more natural to hold down the shift key to set way points for the blaster launcher.

I find myself constantly pressing the shift could to try and queue them up. This is very weird it cancels the way points because shift changes to another unit. Hmmmmm....

What is even more strange is that left shift does change unit but right shift does not. HAHA I was expecting some kind of pinball behaviour ! LOL.

This is not a pinball machine, not yet at least. I can live without the shift key.

But I would very much like to hold the shift key and then press the button on the GUI that normally goes to the next unit but if shift is hold down it goes to the previous unit. So that shift can function as an operator to go back or to queue commands oh yeeah ! ;) =D (At least for blaster launcher for now, but setting movement way points while the unit is moving could also maybe be interesting to speed up the game somewhat ! ;) add the risk of getting shot because of clicking right after an alien was detected or reaction fire happened lol but this could be funny ! =D hehe hahahaha or a time out could be added to prevent the user from queueing any more movement commands ! ;) every second gained is nice. I imagine green movement icons while the unit is already moving... or perhaps it can even be set while the unit is standing still, some kind of game switch could maybe be applied, maybe alt can be used to switch between these movement modes... very interesting though, this could also be used to make the game run in "real time" apocylpse... ufo 3.... so that this again adds another way to play this old classic ! Awesome ! =D)

**Comment by Warboy1982** [comment]
this would require MAJOR code changes to implement a movement waypoint system, and a real-time mode is completely out of the question. this isn't a bug, this is a suggestion. please only open issues for actual bugs, and make suggestions on the forums instead ;)
