### ISSUE TITLE
Hovering over left or right hand/equiped weapon should show weapon name !

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1367]
Hovering over left or right hand/equiped weapon should show weapon name !
^ I would very much like this, to get the know the weapons of new mods and such

If the hovering lasts long enough, detailed statistics could even be shown for the weapon. Like what is it's maximum range. What is it's accuracy and euhm can it be queued or not maybe... stuff like that be awesome yes !

Make it look militairistic by adding green text, make it a bit big so it don't look cheap but not too big, like starwars hehe.. and some nice border around it... and maybe make it fade in and fade out to give it some really fancy pancy shine... of quality yeah.

Another idea could be to display letters like they get typed into a terminal but like really fast. 

Another idea could be to make it really vague transparent like green text... almost like it was a reading on the gun... but it faded over time because of huge usage of the gun... yes... like a green blob of slimer but vague... yes...

**Comment by MeridianOXC** [comment]
Such feature is not planned.
