### ISSUE TITLE
When a unit kills an alien it might as well stop firing even if it's using auto fire ?!

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1370]
How about it ?

Especially for the mini guns, this would be usefull, though it would be funny if the minigun keeps blasting but come on, after a while that might get annoying, maybe implement a mouse click so the user can cancel the firing to give it a more realistic feel, like you have to cancel the minigun yourself ! LOL. Yes this my surprise some noobs, like WTF ?! Why is my minigun still firing ?! LOL.

It's kinda a waste of time to continue firing and it's a waste of ammo.

Surely there is a button on the gun to stop auto-firing for safety reasons.

Yes ok, the original game had blablabla, but let's make it better. And yes accidents might happen because of it, like shooting somebody else that was behind the alien in the face ! But let's not make the game unnecessary frustrating game.

Because that is what firaxis did with eu xcom and it was a major success. So some slight changes to this game, will just make it better.

At the very least this can be put in as an OPTION.

**Comment by Warboy1982** [comment]
think of it like a fire selection switch on a rifle, you switch the gun to 3-round burst and pull the trigger, three rounds are going to be fired regardless of whether the first shot incapacitates its target
