### ISSUE TITLE
SHOT GUN LIKE WEAPONS SHOULD BE ALLOWED TO FIRE MULTIPLE PROJECTILES AT THE SAME TIME.

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1371]
HAHAHAHAHA GRRRREAT IDEA ! =D

I JUST HAD A GAME WHERE ALIENS ALIGNED THEMSELFES UP AND I HAPPENED TO HAVE A SHOT GUN MOUNTED.

BUT IT ONLY FIRED ONE PROJECTILE, ULTIMATELY LAMENESS, THIS DEFINETLY NEEDS MORE WORK FOR THOSE MODDERS ! =D

SEE ATTACHED SCREENSHOT !
![ShotgunShouldFireMultipleProjectiles](https://user-images.githubusercontent.com/34254801/158083030-35110226-cdb7-40e0-b820-af9f548a43bf.png)

**Comment by Warboy1982** [comment]
they already do

**Comment by SkybuckFlying** [comment]
Don't think so... otherwise I would not have reported so I think... or perhaps bad fluke of luck... bullits flew only towards one alien/cell, not multiple... hmmm..

**Comment by TBeholder** [comment]
This only means whichever mod you are trying does not use these capabilities of OXC Nightly (OXCE adds more shotgun parameters, however).
Several existing mods at https://openxcom.old.mod.io/?filter=t&tag[]=Equipment have shotguns that work like shotguns, with multiple distinct hits. At least Arsenal Expanded, Final Mod Pack, Kronos and X-Com Files do.

**Comment by SkybuckFlying** [comment]
I think this is OpenXcom and not OpenXCom extended...
