### ISSUE TITLE
It should be possible to change ammo on grenade launchers and such for tactical options.

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1372]
I just loaded the grenade launcher with some incendiary grenades then I regretted it because I wanted to test smoke grenades.

So I tried to load it again with smoke grenades but it wouldn't let me do it, it says weapon already loaded.

This kinda sucks, it should be my decision what tactics I want, not the game. I am willing to pay the extra time units for it, to reload it again.

So please enable this, at the very least as an option. Let's make this game much better than the original ! =D
![GrenadeLauncherAllowReloadsWhenFull](https://user-images.githubusercontent.com/34254801/158083713-667edd69-c4c8-470f-b893-65a1315168aa.png)

**Comment by Warboy1982** [comment]
![image](https://user-images.githubusercontent.com/2641237/158098331-fe01c1f2-eebb-475a-a7e9-a108a9b0d79f.png)
