### ISSUE TITLE
Pink Blobs don't go up/down elevators

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1375]
As far as I can tell from having played OpenXCom the pink blobs that shoot green parabolic bullits do not go up and down elevators.
This could cause some issues where AI gets stuck at upper floors where it can't get down via the elevator. It seems to be trying to but it doesn't do it.

**Comment by MeridianOXC** [comment]
Tested with vanilla Battleship. The Silacoids are capable of moving up and down the elevators. Closing as invalid.

PS: all aliens use the same AI.

**Comment by SkybuckFlying** [comment]
Silacoids are purple and crawl over the floor. The pink blob I was writing about are the floating pink blobs that should green bullits. Tier 5 I believe.

**Comment by MeridianOXC** [comment]
Re-tested on vanilla Battleship and Celatids. Celatids are perfectly capable of moving up and down the elevators. Still closed as invalid.

**Comment by SkybuckFlying** [comment]
Not that you mention it, perhaps I did see a pink blob go down the elevator in another game, maybe it's situational, or maybe the pink blob decided to ambush the elevator.
