### ISSUE TITLE
Unable to get out of Storage Space Exceeded Loop

### ISSUE THREAD

**Issue by Flash1963** [OpenXcom/OpenXcom#1377]
I am stuck in a loop after completing a mission where prisoners have been captured:

1. Once mission ends, message comes up "Storage Space Exceeded". Click OK.
2. In the Sell Items/Sack Personnel screen, the option to "Remove" prisons is missing. Can only select "Transfer".
3. I selected the number of prisoners that will free up space and attempt to transfer them to the other base.
4. It once again brings me back to the Transfer screen with the only options of Transfer or Cancel.
5. No matter which option you use, you are not able to transfer or remove.

I have added more prison cells, reduced the number of prisoners and tried to play different missions with no change.
At this point, I just close the game and am unable to proceed any further. Attached are screenshots and the game .sav file.

Thanks for your help,
Steve

Before reporting a bug, please check what isn't a bug: https://openxcom.org/bug-tracker/

Include the following information, if applicable:

* IMPORTANT: Step-by-step to reproduce the bug. We need to be able to reproduce the bug to fix it! Savegames are appreciated.
* Complete description of the bug: what went wrong, when did it happen, what were you doing, what was the game doing, etc.
* Any relevant error messages, openxcom.log, screenshots, etc.
* If you were using mods, narrow down the broken mod(s) and report it to the mod author first.

You can attach files by 
![IMG_1855](https://user-images.githubusercontent.com/104308524/164978378-2cfde1fe-f931-4cc0-83be-f6ef4cd9d665.jpg)
![IMG_1856](https://user-images.githubusercontent.com/104308524/164978379-75f9e790-66e7-4ee7-9a93-1b43a6c4839b.jpg)
![IMG_1857](https://user-images.githubusercontent.com/104308524/164978380-8ce50fda-3599-4bb6-9399-721ed04cba05.jpg)
![IMG_1858](https://user-images.githubusercontent.com/104308524/164978382-051291fd-41c7-4d9e-b4af-680de289c29a.jpg)
![IMG_1859](https://user-images.githubusercontent.com/104308524/164978383-4a0388bc-5cdf-4ee2-b5c2-09d09df4fb82.jp
[1 Saved Game.zip](https://github.com/OpenXcom/OpenXcom/files/8549757/1.Saved.Game.zip)
g)
![IMG_1853](https://user-images.githubusercontent.com/104308524/164978384-d36610e5-01e9-45cc-b961-b90400fe0536.jpg)
![IMG_1854](https://user-images.githubusercontent.com/104308524/164978385-26fbd299-85b0-45af-9a9f-bd08f3869883.jpg)
dragging-and-dropping them here.

-->

**Comment by SupSuper** [comment]
You need to get rid of items, not prisoners

**Comment by MeridianOXC** [comment]
Tested with the attached save file. Selling items is enough to be able to continue. Closing as solved.
