### ISSUE TITLE
Incorrect Bio Drone explosion

### ISSUE THREAD

**Issue by ufomesh** [OpenXcom/OpenXcom#1379]
I'm playing OpenXcom latest (for now) Nightly openxcom_git_master_2022_04_29_0633 TFTD and encountered a strange bug with Bio Drone explosion after shooting it. The burned out area isn't round after it explodes, there are at least 2 diagonal beams from the center with a small space between the main spot and then a beam. These beams apply damage too of course.
There're 2 states in savefiles: before and after explosion. To check you need just to shoot the nearby Bio Drone.
Save files: [xcom2.zip](https://github.com/OpenXcom/OpenXcom/files/8778147/xcom2.zip)

Some screenshots:
![biodroneAlive](https://user-images.githubusercontent.com/20906245/170465482-db82256f-5f9b-4df4-95d6-e29ffcb280a1.png)
![biodroneDead](https://user-images.githubusercontent.com/20906245/170465513-d5b73aca-477e-4b53-96bc-c58585214157.png)

**Comment by MeridianOXC** [comment]
This is completely normal.
The blinking green start tiles are "invulnerable", thus no burning and no smoke on them.

**Comment by MeridianOXC** [comment]
Closing as not a bug.
