### ISSUE TITLE
help with compiling in Linux. Fail for file CrossPlatform.cpp

### ISSUE THREAD

**Issue by tho1** [OpenXcom/OpenXcom#1381]
Trying to compile the OpenXCom using cmake in Linux environment.

Attached the CMakeCache.txt.
[CMakeCache.txt](https://github.com/OpenXcom/OpenXcom/files/8858657/CMakeCache.txt)

Below is the log.

cmake --build .
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
found SDL 1.2.15 (/usr/lib64:/usr/include/SDL)
found SDL_mixer 1.2.12 (/usr/lib64:/usr/include/SDL)
found SDL_gfx 2.0.26 (/usr/lib64:/usr/include/SDL)
found SDL_image 1.2.12 (/usr/lib64:/usr/include/SDL)
found yaml-cpp(/usr/local/lib64:/usr/local/include;/usr/local/include/..)
found openGL (/usr/lib64/libGL.so;/usr/lib64/libGLU.so)
git found: /usr/bin/git
version:1.0.b623788a0
Found doxygen:/usr/bin/doxygen
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/home/work/OpenXcom
[  0%] Building CXX object src/CMakeFiles/openxcom.dir/lodepng.cpp.o
[  0%] Building CXX object src/CMakeFiles/openxcom.dir/main.cpp.o
... skip the successful one. 
[ 31%] Building CXX object src/CMakeFiles/openxcom.dir/Engine/CrossPlatform.cpp.o
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp: In function ‘std::vector<std::__cxx11::basic_string<char> > OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)’:
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:461:2: error: ‘DIR’ was not declared in this scope
  DIR *dp = opendir(path.c_str());
  ^~~
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:461:7: error: ‘dp’ was not declared in this scope
  DIR *dp = opendir(path.c_str());
       ^~
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:461:7: note: suggested alternative: ‘dup’
  DIR *dp = opendir(path.c_str());
       ^~
       dup
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:461:12: error: ‘opendir’ was not declared in this scope
  DIR *dp = opendir(path.c_str());
            ^~~~~~~
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:461:12: note: suggested alternative: ‘XPending’
  DIR *dp = opendir(path.c_str());
            ^~~~~~~
            XPending
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:473:17: error: ‘readdir’ was not declared in this scope
  while ((dirp = readdir(dp)) != 0)
                 ^~~~~~~
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:473:17: note: suggested alternative: ‘dladdr’
  while ((dirp = readdir(dp)) != 0)
                 ^~~~~~~
                 dladdr
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:475:26: error: invalid use of incomplete type ‘struct OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)::dirent’
   std::string file = dirp->d_name;
                          ^~
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:472:9: note: forward declaration of ‘struct OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)::dirent’
  struct dirent *dirp;
         ^~~~~~
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:475:28: error: invalid use of incomplete type ‘struct OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)::dirent’
   std::string file = dirp->d_name;
                            ^~~~~~
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:472:9: note: forward declaration of ‘struct OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)::dirent’
  struct dirent *dirp;
         ^~~~~~
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:489:2: error: ‘closedir’ was not declared in this scope
  closedir(dp);
  ^~~~~~~~
/mnt/home/work/OpenXcom/src/Engine/CrossPlatform.cpp:489:2: note: suggested alternative: ‘close’
  closedir(dp);
  ^~~~~~~~
  close
make[2]: *** [src/CMakeFiles/openxcom.dir/build.make:1330: src/CMakeFiles/openxcom.dir/Engine/CrossPlatform.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:161: src/CMakeFiles/openxcom.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by SupSuper** [comment]
Does your Linux environment support dirent.h? https://en.wikibooks.org/wiki/C_Programming/POSIX_Reference/dirent.h

**Comment by tho1** [comment]
Also tried to follow https://www.ufopaedia.org/index.php/Compiling_with_Make_(OpenXcom)

`make -d  -f Makefile.simple`

   Considering target file '../obj/CrossPlatform.o'.
     File '../obj/CrossPlatform.o' does not exist.
     Looking for an implicit rule for '../obj/CrossPlatform.o'.
     Trying pattern rule with stem 'CrossPlatform'.
     Trying implicit prerequisite 'CrossPlatform.cpp'.
     Trying pattern rule with stem 'CrossPlatform'.
     Trying implicit prerequisite 'Basescape/CrossPlatform.cpp'.
     Trying pattern rule with stem 'CrossPlatform'.
     Trying implicit prerequisite 'Battlescape/CrossPlatform.cpp'.
     Trying pattern rule with stem 'CrossPlatform'.
     Trying implicit prerequisite 'Engine/CrossPlatform.cpp'.
     Found an implicit rule for '../obj/CrossPlatform.o'.
      Considering target file 'Engine/CrossPlatform.cpp'.
       Finished prerequisites of target file 'Engine/CrossPlatform.cpp'.
      No need to remake target 'Engine/CrossPlatform.cpp'.
     Finished prerequisites of target file '../obj/CrossPlatform.o'.
    Must remake target '../obj/CrossPlatform.o'.
g++ -O2 -Wall -Wextra -rdynamic  -D GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL -I/usr/local/include/yaml-cpp -c -o ../obj/CrossPlatform.o Engine/CrossPlatform.cpp
Putting child 0x12a9730 (../obj/CrossPlatform.o) PID 22743 on the chain.
Live child 0x12a9730 (../obj/CrossPlatform.o) PID 22743 
Engine/CrossPlatform.cpp: In function ‘std::vector<std::__cxx11::basic_string<char> > OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)’:
Engine/CrossPlatform.cpp:462:2: error: ‘DIR’ was not declared in this scope
  DIR *dp = opendir(path.c_str());
  ^~~
Engine/CrossPlatform.cpp:462:7: error: ‘dp’ was not declared in this scope
  DIR *dp = opendir(path.c_str());
       ^~
Engine/CrossPlatform.cpp:462:7: note: suggested alternative: ‘dup’
  DIR *dp = opendir(path.c_str());
       ^~
       dup
Engine/CrossPlatform.cpp:462:12: error: ‘opendir’ was not declared in this scope
  DIR *dp = opendir(path.c_str());
            ^~~~~~~
Engine/CrossPlatform.cpp:462:12: note: suggested alternative: ‘XPending’
  DIR *dp = opendir(path.c_str());
            ^~~~~~~
            XPending
Engine/CrossPlatform.cpp:474:17: error: ‘readdir’ was not declared in this scope
  while ((dirp = readdir(dp)) != 0)
                 ^~~~~~~
Engine/CrossPlatform.cpp:474:17: note: suggested alternative: ‘dladdr’
  while ((dirp = readdir(dp)) != 0)
                 ^~~~~~~
                 dladdr
Engine/CrossPlatform.cpp:476:26: error: invalid use of incomplete type ‘struct OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)::dirent’
   std::string file = dirp->d_name;
                          ^~
Engine/CrossPlatform.cpp:473:9: note: forward declaration of ‘struct OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)::dirent’
  struct dirent *dirp;
         ^~~~~~
Engine/CrossPlatform.cpp:476:28: error: invalid use of incomplete type ‘struct OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)::dirent’
   std::string file = dirp->d_name;
                            ^~~~~~
Engine/CrossPlatform.cpp:473:9: note: forward declaration of ‘struct OpenXcom::CrossPlatform::getFolderContents(const string&, const string&)::dirent’
  struct dirent *dirp;
         ^~~~~~
Engine/CrossPlatform.cpp:490:2: error: ‘closedir’ was not declared in this scope
  closedir(dp);
  ^~~~~~~~
Engine/CrossPlatform.cpp:490:2: note: suggested alternative: ‘close’
  closedir(dp);
  ^~~~~~~~
  close
Reaping losing child 0x12a9730 PID 22743 
make: *** [Makefile.simple:61: ../obj/CrossPlatform.o] Error 1
Removing child 0x12a9730 PID 22743 from chain.

**Comment by R1dO** [comment]
Got asked on discord if i could weigh in.

First thing i'd like to do is to rule out wrong inclusion of `dirent.h` since that is what the current discussion is focused on.
Could you attach the file `CXX.includecache` from your failing cmake builds?

Since i do not know your setup try `find /mnt/home/work/OpenXcom/ -iname cxx.includecache` in order to find this file.

---

Another option could be that your compiler cache is somehow broken and/or out of date (since `Makefile.simple` has the same problem).
Could you try the following commands from within the openxcom folder (`/mnt/home/work/OpenXcom/`).
```
cmake -B build.dirent
cmake --build build.dirent
```
This will perform all setup and compilation steps from within a folder called `build.dirent` in order to keep things separated from your previous tries.

**Comment by tho1** [comment]
Thanks r1dO.
This is the one with issue.

 [CXX.includecache.txt] (https://github.com/OpenXcom/OpenXcom/files/8874988/CXX.includecache.txt)

`cmake -B build.dirent`

-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
found SDL 1.2.15 (/usr/lib64:/usr/include/SDL)
found SDL_mixer 1.2.12 (/usr/lib64:/usr/include/SDL)
found SDL_gfx 2.0.26 (/usr/lib64:/usr/include/SDL)
found SDL_image 1.2.12 (/usr/lib64:/usr/include/SDL)
found yaml-cpp(/usr/local/lib64:/usr/local/include;/usr/local/include/..)
-- Found OpenGL: /usr/lib64/libGL.so   
found openGL (/usr/lib64/libGL.so;/usr/lib64/libGLU.so)
-- Found Git: /usr/bin/git (found version "2.17.1") 
git found: /usr/bin/git
version:1.0.b623788a0-dirty
Found doxygen:/usr/bin/doxygen
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/home/work/OpenXcom/build.dirent


`cmake --build build.dirent`
[  0%] Building CXX object src/CMakeFiles/openxcom.dir/lodepng.cpp.o
[  0%] Building CXX object src/CMakeFiles/openxcom.dir/main.cpp.o
and this time it works, and managed to produce the binary.

I also attached the CXX.includecache that I found in ' build.dirent/src/CMakeFiles/openxcom.dir/'

[CXX.includecache.success.txt](https://github.com/OpenXcom/OpenXcom/files/8875086/CXX.includecache.success.txt)

I did a diff and notice the original failed as many files are missing. maybe the cmake environments in earlier tries are corrupted.  Thanks for everyone's help.

**Comment by tho1** [comment]
Marking the ticket as closed.
