### ISSUE TITLE
Mod Help (EMP Craft Weapon)

### ISSUE THREAD

**Issue by jmcdaniel83** [OpenXcom/OpenXcom#1385]
I'm not sure if this is available in the Ruleset in order to create a mod that I would like to do in order to perform an EMP weapon for aircraft.  I would like this to allow for the aircraft that crash lands to not have any items on the UFO destroyed, basically would allow for all Elerium to be collected during the ground mission.  I could be missing something but don't see this anywhere in the Rulesets.

**Comment by MeridianOXC** [comment]
The chance of a power source exploding is hardcoded at 75%.
Explosion power is hardcoded at 120.
You can't change those, but you can change how resilient the Elerium item is by changing its "armor" property.
Setting it to 999 will suffice :)

**Comment by jmcdaniel83** [comment]
Thaks so much for the feedback!

**Comment by jmcdaniel83** [comment]
Where in the code is this hardcoded?

**Comment by MeridianOXC** [comment]
BattlescapeGenerator::explodePowerSources()

and

ExplosionBState::init()
