### ISSUE TITLE
Battlescape mousewheel scrolling moves the "cursor" to upper left corner

### ISSUE THREAD

**Issue by gioan777** [OpenXcom/OpenXcom#1386]
During Battlescape when I use the mousewheel to change levels, the cursor is moved to the upper left of the screen to the point if you have edge scrolling enabled it moves the screen away every time you use the mouse wheel.

OS: Arch Linux
Version:  openxcom-git aur package commit: e541af492
Other info: I have 3 monitors, not sure if it's important

Steps to reproduce 

1. Launch the game. Fullscreen or windowed doesn't seem to make a difference.
2. Set Battlescape>Edge Sroll to "Auto"
3. Go to battlescape
4. Change levels with the mouse wheel

Attachments: 
Before scrolling with mouse wheel ![Screenshot_20220820_131827](https://user-images.githubusercontent.com/34718752/185743823-5c12b535-4118-47b8-83fe-e98f64127684.png)
Immediately after (notice the cuboid on the upper left of the screen): ![Screenshot_20220820_131829](https://user-images.githubusercontent.com/34718752/185743850-8399fb10-db90-4187-89c2-2b499cda4a4d.png)
options.cfg [options.cfg.zip](https://github.com/OpenXcom/OpenXcom/files/9386989/options.cfg.zip)

EDIT: Did some extra testing in a couple of VMs. In an EndeavorOS VM I could reproduce the bug, I tried both the AUR package and git clone and building it directly.
In a Windows VM (I used [openxcom_git_master_2022_08_16_1031.exe](https://openxcom.org/git_builds/openxcom_git_master_2022_08_16_1031.exe) from the Downloads page) the problem doesn't seem to exist there.

**Comment by SupSuper** [comment]
This seems to be a bug in sdl12-compat, it should be fixed in the next version: https://github.com/libsdl-org/sdl12-compat/issues/215
