### ISSUE TITLE
Impossible to turn "difficultyDemigod" on

### ISSUE THREAD

**Issue by TCH68k** [OpenXcom/OpenXcom#1390]
It cannot be turned on in the game, there is no such mod.
If i edit `$HOME/.config/openxcom/options.cfg` and add it either to `options` or `mods` it has no effect and the game removes it after starting.

**Comment by SupSuper** [comment]
It's not an option, it's a mod.

**Comment by TCH68k** [comment]
And where is this mod exactly can be downloaded from? If i search on the mods forum for the expression _"difficultyDemigod"_, then i get two topics, where people are talking _"OXCE"_, which i can download it from here: https://openxcom.org/forum/index.php/topic,5258.0.html
For windows and Ubuntu Docker or macOS. I have neither.
What is a _"mod"_ excatly? Is it an external file/pack put into some directory of OpenXCom? Or is it a source patch which will alter the resulting binary after compilation?

**Comment by TCH68k** [comment]
I've found the references in `src/Mod/Mod.cpp`:
```
	_difficultyDemigod = doc["difficultyDemigod"].as<bool>(_difficultyDemigod);
```
So, it can be loaded from an external YAML file. How? I put a file `x.rul` into `/root/.local/share/openxcom/mods/` with the following content:
```
mods:
  - active: true
    id: difficultyDemigod
options:
  difficultyDemigod: 1
```

**Comment by TCH68k** [comment]
Okay, i got it, i found the rulesets in `/usr/local/share/openxcom/standard/xcom1/` and added `difficultyDemigod: true` to the file `difficulty.rul` and that works.

**Comment by MeridianOXC** [comment]
It's documented here: https://www.ufopaedia.org/index.php/Ruleset_Reference_Nightly_(OpenXcom)

**Comment by TCH68k** [comment]
Thanks man.
