### ISSUE TITLE
Passthrough MIDI not supported

### ISSUE THREAD

**Issue by bleggett** [OpenXcom/OpenXcom#1393]
If I have a real MIDI device plugged in (say an MT-32 or Roland SC55) and set within Windows as the default MIDI output device, there does not seem to be a way for OpenXcom to simply pass through to that device as the default system-level MIDI output - it always emulates MIDI.

It would be good to have a simple passthrough option, much like DOSBox and ScummVM.

**Comment by HunterZ** [comment]
It actually does support this, but the problem is that modern Windows doesn't provide MIDI device selection. You need to use something like this to change the default device used by Windows: https://coolsoft.altervista.org/en/midimapper

Another option would be for the game itself to provide device selection.

**Comment by maximilien-noal** [comment]
Would be nice to be able to use the real OPL3 from my Windows 98 machine thanks to a MIDI passthrough.

OpenXCom on vintage hardware...

But it's really not a gift to ask for support from a developer point of view of that ancient relic of an OS. Same for Windows XP.

**Comment by SupSuper** [comment]
I don't think SDL_Mixer supports MIDI devices, would have to look into alternatives.

**Comment by maximilien-noal** [comment]
PortMIDI looks promising:

https://github.com/PortMidi/portmidi

**Comment by HunterZ** [comment]
> ```
> It actually does support this, but the problem is that modern Windows doesn't provide MIDI device selection, so it always uses the built in software synthesizer by default. You need to use something like this to change the default device used by Windows: https://coolsoft.altervista.org/en/midimapper
> ```
> 
> Yup, I'm aware that modern Windows requires that, and I use that exact tool to set the default MIDI device - works fine in ScummVM and DOSBox. OpenXcom does _not_ pass through to my SC-55 like the others do, however, even with that tool - so I think there is still an OpenXcom-specific issue here.

This is weird because I literally just played OpenXcom in Windows 11 x64 with my real SC-88, CM-64, and MT-32 over the weekend. There's got to be something else going on here.

**Comment by HunterZ** [comment]
> PortMIDI looks promising:
> 
> https://github.com/PortMidi/portmidi

Don't know that one, but rtmidi came up when I was looking for examples of how to use Mac's Core MIDI API when adding support to Shockolate a few months ago: https://github.com/thestk/rtmidi

Both libraries appear to have the same very permissive license.

**Comment by SupSuper** [comment]
OpenXcom doesn't try to replicate the original audio drivers. If you use Adlib, you'll only get emulated audio. If you use MIDI, it will either get emulated or sent to a MIDI device depending on platform (assuming your version of X-COM even has MIDI support).

**Comment by bleggett** [comment]
Aight - I re-checked this, and in fact the passthrough **does** work - the volume output from OpenXCOM is lower than Dosbox/ScummVM and so it wasn't triggering the SC-55's channel loudness display enough for me to notice 😩 

Apologies - this is working correctly as @HunterZ described.

**Comment by HunterZ** [comment]
Nice, glad you figured it out! I probably cranked the music volume slider in-game to full without even thinking about it.
