### ISSUE TITLE
Battlescape: Glitchy OGG playback

### ISSUE THREAD

**Issue by hosser** [OpenXcom/OpenXcom#1394]
macOS Monterey 12.6
OpenXcom build 1.0e541af492, built from source
PSX soundtrack files (OGG format, Stereo, 44100Hz) added to 'Resources\TFTD\SOUND' directory
OGG music format selected in Options

Music becomes glitchy and distorted after a few minutes of play. Issue only occurs in the Battlescape, never the GeoScape. Happens after a few minutes, for a few minutes, then returns to normal. Then reoccurs a few minutes later, then back to normal. Etc.

Also worth noting that the issue only occurs in TFTD, not UFO which I played through to completion on this same machine without encountering this issue at all, with that game's OGG soundtrack enabled.

Video of the issue [here](https://youtu.be/fCjGIaIFLdE).

**Comment by SupSuper** [comment]
Fixed by setting `audioSampleRate: 44100`
