### ISSUE TITLE
Fatal Error Openxcom crash when Alien controls Marine with Blaster Launcher

### ISSUE THREAD

**Issue by Jaggedeye** [OpenXcom/OpenXcom#1408]
While in the Battle screen during a turn where the Etheral Leader mind controls my soldier holding the Blaster Launcher the game crashes out. I reloaded the same save and tried the same events and it happened three times the same way. Attached is the Fatal error info and the saved battle game. I am running OpenXcom default installed game with no additional MODS. 
[Crash game 001.zip](https://github.com/OpenXcom/OpenXcom/files/10884979/Crash.game.001.zip)
[Fatal Error Mar 3 2023 Alien Mind Control of Blaster Solider.txt](https://github.com/OpenXcom/OpenXcom/files/10884980/Fatal.Error.Mar.3.2023.Alien.Mind.Control.of.Blaster.Solider.txt)

**Comment by Jaggedeye** [comment]
Upon more inspection of what might be the triggering factor I think it is when the game calls the function for the mind controlled marine that has an empty Blaster Launcher to reload the Launcher or it could be the call to target with the Blaster launcher. I do not know coding so I am only guessing at a place to look. 

I am attaching a similar crash file at a different point in the game.
[Fatal Error Mar 10 2023 Alien Mind Control of Blaster Marine again.log](https://github.com/OpenXcom/OpenXcom/files/10943540/Fatal.Error.Mar.10.2023.Alien.Mind.Control.of.Blaster.Marine.again.log)
[Crash game 002.zip](https://github.com/OpenXcom/OpenXcom/files/10943542/Crash.game.002.zip)

**Comment by SupSuper** [comment]
Fixed in https://github.com/OpenXcom/OpenXcom/commit/6b96200e1abfdea1d0215cd5cefeae7b51f2b99f
