### ISSUE TITLE
Enabling "Alternate craft equipment management" causes desync between listed inventory and actual inventory of craft.

### ISSUE THREAD

**Issue by RLaraIII** [OpenXcom/OpenXcom#1419]
Enabling the option "Alternate craft equipment management" under Advanced -> Extended causes a desync between the shown and actual inventory of a craft. This allows you to keep a weapon in the base, but still usable to the soldiers in the ship.

To reproduce: 
1) With the option disabled, start a new game and note the default equipped items in the skyranger. 
2) Enable the feature and start a new game. The inventories with be desynced (pictured below).

Easiest example is looking at the rocket launcher (unequipped in picture one but usable in picture 2) 

![image](https://github.com/OpenXcom/OpenXcom/assets/61221339/3fa4b74e-89f3-4908-8ea9-2f7906a4af87)

![image_2](https://github.com/OpenXcom/OpenXcom/assets/61221339/934c1b5a-3f6f-43dd-836e-f877299aa9ee)

**Comment by MeridianOXC** [comment]
This is how the feature is supposed to work.

More reading: https://openxcom.org/forum/index.php/topic,10452.msg154661.html#msg154661
