### ISSUE TITLE
[OXCE, New Battle] Soldiers not ranking up or increasing stats after battle

### ISSUE THREAD

**Issue by Spectral-Dreams** [OpenXcom/OpenXcom#1420]
Using Brutal AI OXCE and the Xcom files mod (all downloaded from mod.io) along with the following addons:

![image](https://github.com/OpenXcom/OpenXcom/assets/132994032/264f0b1d-ea43-4aa1-af06-99b8cce96d08)

Here's my xcom files battle.cfg (I edited it by adding more than 30 soldiers because I was not satisfied with the given roster).
https://pastebin.com/c1aMzmew

To reproduce the bug:

1. Start a new battle mission (anything will do)
2. Finish it.
3. The end result screen will show your units gained a +1, 2, 3, or more in certain stats (TU, HP, etc.)
4. Take those same units to another mission (or the same one).
5.  You'll notice the stats remain the same and haven't gone up as they're supposed to.

Please let me know if there's anything else I need to share. Thank you!

**Comment by MeridianOXC** [comment]
That's a feature, not a bug.
New Battle is a single mission simulator, when it's over, nothing is remembered.
