### ISSUE TITLE
[Base Defense] YAML formatting errors on savegame 

### ISSUE THREAD

**Issue by across-the-stars** [OpenXcom/OpenXcom#1422]
I have had my savegame crash on me when it was saved during the first turn of the base defense mission. Values on some fields where saved as strings instead of as integer made YAML::Node::as<uint8> take the values as 0 instead of the real value. Fixing the savegame manually was the only way I could find to have it load again.

Example:
tileIndexSize: "\x04"
tileTotalBytesPer: 23
tileFireSize: "\x01"
tileSmokeSize: "\x01"
tileIDSize: "\x02"
tileSetIDSize: "\x02"
tileBoolFieldsSize: "\x01"
totalTiles: 6250

**Comment by MeridianOXC** [comment]
If I remember correctly this is an issue with yaml-cpp 0.7.x.
If you can, use yaml-cpp 0.6.3 instead.

**Comment by Yankes** [comment]
@across-the-stars What version of code you use? I check year older code and its already have some workaround for bug like this:
[7fe2dd9](https://github.com/OpenXcom/OpenXcom/commit/7fe2dd93bfe590250c563257cd078e8df519bfec)
[09f8473](https://github.com/OpenXcom/OpenXcom/commit/09f8473bc8b91592db01e64fbc6cec7921a2b8ff)

**Comment by across-the-stars** [comment]
I'm on the latest nightly (8d45159bf3e27d6aef62aff6035d9f6a59caf00b), so maybe that's the problem. Cannot downgrade yaml-cpp since that would probably break my install.

**Comment by across-the-stars** [comment]
I'm on the latest nightly (8d45159bf3e27d6aef62aff6035d9f6a59caf00b) so that might be my issue. Cannot really downgrade yaml-cpp without breaking something.

**Comment by Yankes** [comment]
This commit is 2y old, and this is not latest nightly, correct one is my commit:
https://github.com/OpenXcom/OpenXcom/commit/ad854b395794eb55040f070a9e358cdf55767c32
And its have fixes for that.

**Comment by across-the-stars** [comment]
Thanks, I'll switch to that one. The site doesn't have that last nightly, though.

Closing this issue.
