### ISSUE TITLE
Broken links to Linux downloads

### ISSUE THREAD

**Issue by Fixer-007** [OpenXcom/OpenXcom#1440]
If you try downloading OpenXcom app images for linux from https://openxcom.org/git-builds/ it gives "Page not found" error

**Comment by Zelif** [comment]
Anyone wanting a linux release, I now just go to the
` Github->Actions->Latest build->Go down to Artifacts`
Other than that, build it yourself I guess at this point. Doesn't seem like the person doing the linux builds is doing it atm or doesn't know it is down.

**Comment by SupSuper** [comment]
I'm moving the builds to GitHub.
Can you check if the latest AppImage works for you? https://github.com/OpenXcom/OpenXcom/actions/runs/9654138850
