### ISSUE TITLE
No translation files

### ISSUE THREAD

**Issue by drizt** [OpenXcom/OpenXcom#1449]
Github repo doesn't contain translation files. Also no any instruction how to get them. Seems translation located on Transifex but I don't see any Download button. So my question how to get translation files?

**Comment by drizt** [comment]
Thanks. But I think translations (as any other source files) should be allowed for downloading without any account (for package build for example). **actions** is not a place for source files. It contains building articafatcts.

**Comment by SupSuper** [comment]
Transifex doesn't have anonymous access, so this is the only way I could work around it.
The only other option would be for CI to push them to a separate repo and you can grab them from there.

**Comment by drizt** [comment]
Anyway now it's not a problem. I use OXCE it includes all translations in repo.
